// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzVT26tIufhHz5K6PH6vjZHN4zhuKwzFA',
    appId: '1:708008442857:web:19a60ddab0bec1a9ae6978',
    messagingSenderId: '708008442857',
    projectId: 'travel-bd-4c50d',
    authDomain: 'travel-bd-4c50d.firebaseapp.com',
    storageBucket: 'travel-bd-4c50d.firebasestorage.app',
    measurementId: 'G-5F9VK7SMPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVqgpIDMIiJV8cnU1a3P9PANAzP2cp3bE',
    appId: '1:708008442857:android:9edd91ff70b2bfe9ae6978',
    messagingSenderId: '708008442857',
    projectId: 'travel-bd-4c50d',
    storageBucket: 'travel-bd-4c50d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ31kZyrhBc1QWyEU3jWMnqNaioJncArA',
    appId: '1:708008442857:ios:7c39d4065bf2f118ae6978',
    messagingSenderId: '708008442857',
    projectId: 'travel-bd-4c50d',
    storageBucket: 'travel-bd-4c50d.firebasestorage.app',
    iosClientId: '708008442857-ofu4utn1h760jottkkc1pvc7pthtpij1.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelBd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ31kZyrhBc1QWyEU3jWMnqNaioJncArA',
    appId: '1:708008442857:ios:7c39d4065bf2f118ae6978',
    messagingSenderId: '708008442857',
    projectId: 'travel-bd-4c50d',
    storageBucket: 'travel-bd-4c50d.firebasestorage.app',
    iosClientId: '708008442857-ofu4utn1h760jottkkc1pvc7pthtpij1.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelBd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzVT26tIufhHz5K6PH6vjZHN4zhuKwzFA',
    appId: '1:708008442857:web:9111c22605a098dfae6978',
    messagingSenderId: '708008442857',
    projectId: 'travel-bd-4c50d',
    authDomain: 'travel-bd-4c50d.firebaseapp.com',
    storageBucket: 'travel-bd-4c50d.firebasestorage.app',
    measurementId: 'G-9REC1PLVE4',
  );

}